# Generated by Django 4.2.6 on 2023-11-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile1',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
