# Generated by Django 4.2.6 on 2023-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_workerprofile1_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
