# Generated by Django 4.2.6 on 2023-11-27 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0005_booking_is_approved_delete_booking1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.servicecategory'),
        ),
        migrations.DeleteModel(
            name='Notificationservice',
        ),
    ]
