# Generated by Django 4.2.6 on 2023-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0006_booking_category_delete_notificationservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
