# Generated by Django 4.2.6 on 2023-12-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0010_review_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='documents',
            field=models.FileField(null=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='workerprofile1',
            name='documents',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
