# Generated by Django 4.2.6 on 2023-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0011_workerprofile_documents_workerprofile1_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile1',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile1',
            name='newcategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
