# Generated by Django 4.2.6 on 2023-12-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0012_workerprofile1_is_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile1',
            name='is_category',
        ),
    ]
