# Generated by Django 4.2.6 on 2023-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0013_remove_workerprofile1_is_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile1',
            name='newcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
