# Generated by Django 4.2.6 on 2023-12-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0014_alter_workerprofile1_newcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
