# Generated by Django 4.2.6 on 2023-12-19 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0015_service_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.workerprofile'),
        ),
    ]
