# Generated by Django 4.2.6 on 2023-12-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0016_alter_service_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=20),
        ),
    ]
