# Generated by Django 4.2.6 on 2024-01-08 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0018_alter_workerprofile1_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile1',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceapp.notification'),
        ),
    ]
