# Generated by Django 4.2.6 on 2024-01-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0019_workerprofile1_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile1',
            name='notification',
        ),
    ]
